### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "password": "supersecret123"

}

### Sign in as an existing user
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}


### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=test50@test.com

### Delete a user given id
DELETE http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "password": "supersecret123"
}